1._Version_:

In [139]:
import numpy as np
print("Git Revision: {}".format(np.version.git_revision))
print("Version: {}".format(np.version.version))
print("Full Version: {}".format(np.version.full_version))
print("Release: {}".format(np.version.release))

Git Revision: f8021557bb402c514d8be5a9f005c1565fd57eb8
Version: 1.23.4
Full Version: 1.23.4
Release: True


2._1D & 2D Arrays_

In [140]:
# 1D Array
a = np.array([1, 2, 3])
print(f"Type: {type(a)}")
print(f"1D Shape: {a.shape}")
print(f"1D All: {a.all()}")
print(f"1D Any: {a.any()}")

#2D Array
b = np.array([[1,2,3], [4,5,6]])
print(f"2D Shape: {b.shape}") # 2 Rows and 3 Columns
print(b[0, 0], b[0, 1], b[1, 0])
c = b.T
print(f"2D Transpose: {b.T}")
print(f"2D Shape: {c.shape}")



Type: <class 'numpy.ndarray'>
1D Shape: (3,)
1D All: True
1D Any: True
2D Shape: (2, 3)
1 2 4
2D Transpose: [[1 4]
 [2 5]
 [3 6]]
2D Shape: (3, 2)


3._zeros, ones, full, eye, random_

In [141]:
# Zeros
a = np.zeros((2,2), dtype=int) # default float type
print(f"Zeros Int: {a}")
a = np.zeros((2,2), dtype=str) 
print(f"Zeros String: {a}")

# Ones
a = np.ones((2,2), dtype=int) # default float type
print(f"Ones Int: {a}")
a = np.ones((2,2), dtype=str)
print(f"Ones String: {a}")

# Full
a = np.full((2,2), 7, dtype=int) # default float type
print(f"Full Int: {a}")
a = np.full((2,2), "empty", dtype=str) # only first char of string used for filling. 
print(f"Full String: {a}")

# Eye
a = np.eye(2, dtype=int) # default float type
print(f"Eye Int: {a}")
print(f"Eye Multiplied: {a*8}")

# random
print(f"Random: {np.random.random((2,2))}")
print(f"Random rand: {np.random.rand(3,2)}")
print(f"Random rand from gaussian distribution: {np.random.randn(3,2)}")
print(f"Random Beta distribution: {np.random.beta(3,2)}")
print(f"Random State: {np.random.RandomState()}")


Zeros Int: [[0 0]
 [0 0]]
Zeros String: [['' '']
 ['' '']]
Ones Int: [[1 1]
 [1 1]]
Ones String: [['1' '1']
 ['1' '1']]
Full Int: [[7 7]
 [7 7]]
Full String: [['e' 'e']
 ['e' 'e']]
Eye Int: [[1 0]
 [0 1]]
Eye Multiplied: [[8 0]
 [0 8]]
Random: [[0.12739004 0.39302166]
 [0.71849262 0.04425358]]
Random rand: [[0.91517051 0.66283649]
 [0.70647164 0.33177161]
 [0.56984565 0.76062406]]
Random rand from gaussian distribution: [[ 1.27656391  1.45329421]
 [-0.46450789  0.97437681]
 [-0.15266736  0.34487995]]
Random Beta distribution: 0.8436812283052622
Random State: RandomState(MT19937)


4._Array indexing_

In [142]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(f"Slicing: {a[:2, 1:3]}")
b = a
b[2,0] = 77
print(f"a and b are shallow copied {a[2,0]} and {b[2,0]}")
print(f"rows: {a[:, 0:3]}")
print(f"rows: {a[0:2, :]}")

Slicing: [[2 3]
 [6 7]]
a and b are shallow copied 77 and 77
rows: [[ 1  2  3]
 [ 5  6  7]
 [77 10 11]]
rows: [[1 2 3 4]
 [5 6 7 8]]


5._Mutating Array_

In [143]:
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
b = np.array([0, 2, 0, 1]) # Acts as indices
print(a[np.arange(4), b])
a[np.arange(4), b] += 10
print(f"Mutated specific index {a}")

[ 1  6  7 11]
Mutated specific index [[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


6._Boolean Array indexing_

In [144]:
a = np.array([[1,2], [3, 4], [5, 6]])
bool_idx = (a>2)
print(f"Bool indexes {bool_idx}")
print(a[bool_idx]) # or a[a>2]

Bool indexes [[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]


7._Array Math_

In [145]:
%%time
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

print(f"Add: {np.add(x, y)}") # same as x + y
print(f"Sub: {np.subtract(x, y)}") # same as x - y
print(f"Mul: {np.multiply(x, y)}") # same as x * y
print(f"Div: {np.divide(x, y)}") # same as x / y
print(f"Mod: {np.mod(x, y)}") # same as x % y
print(f"Sqrt: {np.sqrt(x)}") # same as x root
print(f"Square: {np.square(x)}") # same as x square
print(f"Dot: {np.dot(x, y)}") # same as x dot y as in MATLAB
print(f"Sum: {np.sum(x)}") # sum of all elements in array
print(f"Sum: {np.sum(x, axis=0)}") # sum of all elements in across columns.
print(f"Sum: {np.sum(x, axis=1)}") # sum of all elements in across rows.


Add: [[ 6.  8.]
 [10. 12.]]
Sub: [[-4. -4.]
 [-4. -4.]]
Mul: [[ 5. 12.]
 [21. 32.]]
Div: [[0.2        0.33333333]
 [0.42857143 0.5       ]]
Mod: [[1. 2.]
 [3. 4.]]
Sqrt: [[1.         1.41421356]
 [1.73205081 2.        ]]
Square: [[ 1.  4.]
 [ 9. 16.]]
Dot: [[19. 22.]
 [43. 50.]]
Sum: 10.0
Sum: [4. 6.]
Sum: [3. 7.]
CPU times: total: 0 ns
Wall time: 5.38 ms


8._Broadcasting_

In [146]:
%%timeit -r 2 -n 2
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)
e = np.empty([2,2])
print(f"Empty Array: {e}")
print(f"Empty Array Like: {y}")
print(f"Is x == y? {x == y}")
t = np.tile(v, (4, 1))
print(f"Tile an array and shape: {t}, {t.shape}")
y = x + t # Add x and vv elementwise.
print(f"Element wise addition between x and t: {y}")

Empty Array: [[19. 22.]
 [43. 50.]]
Empty Array Like: [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Is x == y? [[ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]]
Tile an array and shape: [[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]], (4, 3)
Element wise addition between x and t: [[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
Empty Array: [[19. 22.]
 [43. 50.]]
Empty Array Like: [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Is x == y? [[ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]]
Tile an array and shape: [[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]], (4, 3)
Element wise addition between x and t: [[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
Empty Array: [[19. 22.]
 [43. 50.]]
Empty Array Like: [[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
Is x == y? [[False  True False]
 [False  True False]
 [False  True False]
 [False  True False]]
Tile an array and shape: [[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]], (4, 3)
Element wise addi