1. _Version_:

In [102]:
import numpy as np
print("Git Revision: {}".format(np.version.git_revision))
print("Version: {}".format(np.version.version))
print("Full Version: {}".format(np.version.full_version))
print("Release: {}".format(np.version.release))

Git Revision: f8021557bb402c514d8be5a9f005c1565fd57eb8
Version: 1.23.4
Full Version: 1.23.4
Release: True


2. _1D & 2D Arrays_

In [103]:
# 1D Array
a = np.array([1, 2, 3])
print(f"Type: {type(a)}")
print(f"1D Shape: {a.shape}")
print(f"1D All: {a.all()}")
print(f"1D Any: {a.any()}")

#2D Array
b = np.array([[1,2,3], [4,5,6]])
print(f"2D Shape: {b.shape}") # 2 Rows and 3 Columns
print(b[0, 0], b[0, 1], b[1, 0])
c = b.T
print(f"2D Transpose: {b.T}")
print(f"2D Shape: {c.shape}")



Type: <class 'numpy.ndarray'>
1D Shape: (3,)
1D All: True
1D Any: True
2D Shape: (2, 3)
1 2 4
2D Transpose: [[1 4]
 [2 5]
 [3 6]]
2D Shape: (3, 2)


3. _zeros, ones, full, eye, random_

In [104]:
# Zeros
a = np.zeros((2,2), dtype=int) # default float type
print(f"Zeros Int: {a}")
a = np.zeros((2,2), dtype=str) 
print(f"Zeros String: {a}")

# Ones
a = np.ones((2,2), dtype=int) # default float type
print(f"Ones Int: {a}")
a = np.ones((2,2), dtype=str)
print(f"Ones String: {a}")

# Full
a = np.full((2,2), 7, dtype=int) # default float type
print(f"Full Int: {a}")
a = np.full((2,2), "empty", dtype=str) # only first char of string used for filling. 
print(f"Full String: {a}")

# Eye
a = np.eye(2, dtype=int) # default float type
print(f"Eye Int: {a}")
print(f"Eye Multiplied: {a*8}")

# random
print(f"Random: {np.random.random((2,2))}")
print(f"Random rand: {np.random.rand(3,2)}")
print(f"Random rand from gaussian distribution: {np.random.randn(3,2)}")
print(f"Random Beta distribution: {np.random.beta(3,2)}")
print(f"Random State: {np.random.RandomState()}")


Zeros Int: [[0 0]
 [0 0]]
Zeros String: [['' '']
 ['' '']]
Ones Int: [[1 1]
 [1 1]]
Ones String: [['1' '1']
 ['1' '1']]
Full Int: [[7 7]
 [7 7]]
Full String: [['e' 'e']
 ['e' 'e']]
Eye Int: [[1 0]
 [0 1]]
Eye Multiplied: [[8 0]
 [0 8]]
Random: [[0.52069711 0.85594105]
 [0.67629695 0.95073007]]
Random rand: [[0.84106133 0.91989746]
 [0.01088049 0.89453167]
 [0.84126235 0.14134094]]
Random rand from gaussian distribution: [[ 1.66064409  1.11069876]
 [-1.36521325  0.65004207]
 [-0.83322307 -0.71654329]]
Random Beta distribution: 0.3498400243331455
Random State: RandomState(MT19937)


4. _Array indexing_

In [105]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(f"Slicing: {a[:2, 1:3]}")
b = a
b[2,0] = 77
print(f"a and b are shallow copied {a[2,0]} and {b[2,0]}")
print(f"rows: {a[:, 0:3]}")
print(f"rows: {a[0:2, :]}")

Slicing: [[2 3]
 [6 7]]
a and b are shallow copied 77 and 77
rows: [[ 1  2  3]
 [ 5  6  7]
 [77 10 11]]
rows: [[1 2 3 4]
 [5 6 7 8]]


5. _Mutating Array_

In [109]:
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
b = np.array([0, 2, 0, 1]) # Acts as indices
print(a[np.arange(4), b])

[ 1  6  7 11]
